### ISSUE TITLE
No way to navigate to pages

### ISSUE THREAD

**Issue by daviddarnes** [knowncolor/deliberately-simple#1]
Pages appear to be designed ok but are not accessible. A simple navigation would solve this.

**Comment by knowncolor** [comment]
@daviddarnes Thanks for raising this, I'm happy to fix it but I'm not clear on what you mean. Not accessible in terms of being able to be found and clicked on (i.e. not navigable), or not meeting [accessibility guidelines](http://www.w3.org/standards/webdesign/accessibility)?

**Comment by daviddarnes** [comment]
@knowncolor I just mean that the theme doesn't provide a link to those pages. [A simple menu](http://anchorcms.com/docs/function-reference/menus) in the header of the theme will solve this quite easily. Here's one I've created in another theme https://github.com/daviddarnes/ticket/blob/master/header.php#L36-L42

**Comment by daviddarnes** [comment]
Top notch work! :star2:
